version: "3.9"

services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      PGUSER: POSTGRES_USER
      PGPASSWORD: POSTGRES_PASSWORD
      PGDATABASE: POSTGRES_DB
      PGHOST: db
      PGPORT: 5432

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data

# Persisting data in this volume is not working.
volumes:
  db_data:
